language: java

jdk:
  - oraclejdk8

sudo: required

cache:
  apt: true
  directories:
  - $HOME/.m2
  - $HOME/.embedmongo

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz

after_success:
  - mvn clean test jacoco:report coveralls:report
