language: java

jdk:
  - oraclejdk8

sudo: false

cache:
  apt: true
  directories:
  - $HOME/.m2
  - $HOME/.embedmongo

addons:
  apt:
    packages:
    - graphviz

after_success:
  - mvn clean cobertura:cobertura coveralls:report
