//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.02 at 11:45:06 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.leishvl.tapir.geo;
