//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.28 at 03:53:32 PM CET 
//


package io.leishvl.tapir.vcard;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.leishvl.tapir.vcard package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FN_QNAME = new QName("http://www.w3.org/2001/vcard-rdf/3.0#", "FN");
    private final static QName _TITLE_QNAME = new QName("http://www.w3.org/2001/vcard-rdf/3.0#", "TITLE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.leishvl.tapir.vcard
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VCARD }
     * 
     */
    public VCARD createVCARD() {
        return new VCARD();
    }

    /**
     * Create an instance of {@link SimpleElement }
     * 
     */
    public SimpleElement createSimpleElement() {
        return new SimpleElement();
    }

    /**
     * Create an instance of {@link TEL }
     * 
     */
    public TEL createTEL() {
        return new TEL();
    }

    /**
     * Create an instance of {@link EMAIL }
     * 
     */
    public EMAIL createEMAIL() {
        return new EMAIL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vcard-rdf/3.0#", name = "FN")
    public JAXBElement<SimpleElement> createFN(SimpleElement value) {
        return new JAXBElement<SimpleElement>(_FN_QNAME, SimpleElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vcard-rdf/3.0#", name = "TITLE")
    public JAXBElement<SimpleElement> createTITLE(SimpleElement value) {
        return new JAXBElement<SimpleElement>(_TITLE_QNAME, SimpleElement.class, null, value);
    }

}
