//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 11:28:43 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rs.tdwg.org/tapir/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.leishvl.core.xml.tdwg.tapir;
